version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - manageyourmoney
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: aklamaash
      POSTGRES_PASSWORD: akla1234
      POSTGRES_DB: manageyourmoney
    ports:
      - "5432:5432"
    volumes:
      - manageyourmoneydata:/var/lib/postgresql/data
    networks:
      - manageyourmoney
 
volumes:
  node_modules:
  manageyourmoneydata:

networks:
  manageyourmoney:
    driver: bridge
